### PR TITLE
Import data avantikaa

### LINKED ISSUE #9: Import packages and preprocess the data
**All the functions mentioned in this issue must be solved for this issue to be solved completely.**

The basic required packages have been given in requirements.txt which can be installed using the pip command given in the usage section.

Import the packages in the "Import Packages" section in main.ipynb

Clean and preprocess the data after importing the data and the required packages. 

Within preprocessing, the following steps must be covered:
**1)Convert all the text to lowercase.**

Function to edit in main.ipynb:
def toLowerCase(corpus)

**2)Tokenize the text into a list of sentences.**

Function to edit in main.ipynb:
def sentence_tokenize(corpus)

**3)Tokenize a sentence into a bag of words.**

Function to edit in main.ipynb:
def word_tokenize(sentence):

**4)Convert a sentence into an equivalent list of characters without punctuation(.,?,!)**

Function to edit in main.ipynb:
def listOfAlphabets(sentence):

### PR DESCRIPTION
**Pull request by daviddavo**
Fixes #9 

Changes: 
- [x] Convert all text to lowercase
- [x] Tokenize the text into a list of sentences
- [x] Tokenize a sentence into a bag of words
- [x] Convert a sentence into an equivalent list of characters without punctuation

### CODE REVIEW

**Comment by vinamrak** [comment]
@daviddavo In step 4 for preprocessing, you need to convert the sentence into a list of characters and not words.

**Comment by vinamrak** [comment]
@daviddavo in step 4 of preprocessing, the function definition is correct. Just return the list of characters for a sentence instead of the words in that sentence. For example- you have inputted "hello world?!." as the input but the words "hello" and "world" are being shown as output. The correct output should be ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd'].

**Comment by daviddavo** [comment]
I was passing the bagged list of words instead of the sentence in the usage example. If you use a "plain" sentence (a string) the output is as desired.
I don't know if I have to receive the bagged list of words and return a list of characters or if it's already fine as it is.

**Comment by vinamrak** [comment]
@daviddavo yes the last commit is correct. You needed to pass a sentence and get the list of characters.

**Comment by vinamrak** [comment]
Good job @daviddavo your PR has been merged!

**Pull request merged**
